[meta]
title = "Indraneel Mahendrakumar"
description = "Indraneel Mahendrakumar - page not found"
keywords = "portfolio, error"

[[meta.stylesheets]]
link = "colors"
defer = true

[[meta.stylesheets]]
link = "flex"

[[meta.stylesheets]]
link = "markdown"
defer = true

[[meta.stylesheets]]
link = "sizing"

[[meta.stylesheets]]
link = "spacing"

[[meta.stylesheets]]
link = "text"