[meta]
title = "Indraneel Mahendrakumar"
description = "Indraneel Mahendrakumar's website created using Jabberwock."
keywords = "portfolio"
stylesheets = ["colors", "flex", "markdown", "sizing", "spacing", "text"]