[meta]
title = "IsleWard Addon Settings Framework - Indraneel Mahendrakumar"
description = "Indraneel Mahendrakumar's project: IsleWard Addon Settings Framework."
keywords = "portfolio, project"
stylesheets = ["colors", "flex", "markdown", "sizing", "spacing", "text"]