[meta]
title = "Advent of Code - Indraneel Mahendrakumar"
description = "Indraneel Mahendrakumar's project: Advent of Code solutions."
keywords = "portfolio, project"
stylesheets = ["colors", "flex", "markdown", "sizing", "spacing", "text"]