[meta]
title = "GDSerializer - Indraneel Mahendrakumar"
description = "Project: GDSerializer."
keywords = "portfolio, project"
stylesheets = ["colors", "flex", "markdown", "sizing", "spacing", "text"]