[meta]
title = "Improved Insectoids - Indraneel Mahendrakumar"
description = "Indraneel Mahendrakumar's project: Improved Insectoids."
keywords = "portfolio, project"
stylesheets = ["colors", "flex", "markdown", "sizing", "spacing", "text"]