[meta]
title = "Jabberwock - Indraneel Mahendrakumar"
description = "Project: Jabberwock."
keywords = "portfolio, project"

[[meta.stylesheets]]
link = "colors"
defer = true

[[meta.stylesheets]]
link = "flex"

[[meta.stylesheets]]
link = "markdown"
defer = true

[[meta.stylesheets]]
link = "sizing"

[[meta.stylesheets]]
link = "spacing"

[[meta.stylesheets]]
link = "text"