[meta]
title = "Jabberwock - Indraneel Mahendrakumar"
description = "Indraneel Mahendrakumar's project: Jabberwock."
keywords = "portfolio, project"
stylesheets = ["colors", "flex", "markdown", "sizing", "spacing", "text"]