[meta]
title = "MoreLinq - Indraneel Mahendrakumar"
description = "Indraneel Mahendrakumar's project: MoreLinq."
keywords = "portfolio, project"
stylesheets = ["colors", "flex", "markdown", "sizing", "spacing", "text"]