[meta]
title = "Modot - Indraneel Mahendrakumar"
description = "Indraneel Mahendrakumar's project: Modot."
keywords = "portfolio, project"
stylesheets = ["colors", "flex", "markdown", "sizing", "spacing", "text"]