name: Publish GitHub Pages site

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  pages: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint and format
    
    runs-on: ubuntu-latest

    steps:
      - name: Update Rust toolchain
        run: |
          rustup update stable
          rustup update nightly
          rustup default stable
          rustup component add rustfmt --toolchain nightly
      
      - name: Check code formatting
        run: |
          cargo +nightly fmt --check --verbose
      
      - name: Lint code
        run: |
          cargo clippy --verbose -- --deny warnings

  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Update Rust toolchain
        run: |
          rustup update stable
          rustup default stable
      
      - name: Generate site
        run: |
          cargo run --release
      
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/
  
  deploy:
    name: Deploy
    
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4